/**FileOperationListener.java
 * 
 * 05/03/2015
 * 
 * Currently used to signal the file operation events generated by 
 * {@link edu.iupui.sw.simplydrawn.gui.SDMenuBar} to
 * {@link edu.iupui.sw.simplydrawn.canvas.SDCanvas}.
 * 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 *    
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *    
 * 
 * 
 * @author Seth Winfree
 * 
 * @version 0.1
 * 
 */

package edu.iupui.sw.simplydrawn.listener;

public interface FileOperationListener {
	/**
	 * Notifies listeners to attempt to open a file of the appropriate type.  Exceptions must be handled by
	 * the caller
	 * 
	 * @throws Exception
	 */
	public int onFileOpen() throws Exception;
	/**
	 * Notifies listeners to attempt to save a file of the appropriate type.  Exceptions must be handled by
	 * the caller
	 * 
	 * @throws Exception
	 */
	public void onFileSave() throws Exception;
	/**
	 * Notifies listeners to attempt to export a file of the appropriate type.  Exceptions must be handled by
	 * the caller
	 * 
	 * @throws Exception
	 */
	public void onFileExport() throws Exception;
	
}
